spring:
  # 데이터베이스 설정
  datasource:
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: project
    password: _aA123456

  # JPA 설정
  jpa:
    properties:
      hibernate:
        # 실행되는 쿼리를 콘솔에 출력
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create

# 로거 설정
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

